/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./src/components/ui/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./src/components/ui/accordion/AccordionItem.vue')['default']
    AccordionQA: typeof import('./src/components/AccordionQA.vue')['default']
    AccordionTrigger: typeof import('./src/components/ui/accordion/AccordionTrigger.vue')['default']
    AlertDialog: typeof import('./src/components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./src/components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./src/components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./src/components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./src/components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./src/components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./src/components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./src/components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./src/components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    CarGalleryCarousel: typeof import('./src/components/CarGalleryCarousel.vue')['default']
    Carousel: typeof import('./src/components/ui/carousel/Carousel.vue')['default']
    CarouselContent: typeof import('./src/components/ui/carousel/CarouselContent.vue')['default']
    CarouselItem: typeof import('./src/components/ui/carousel/CarouselItem.vue')['default']
    CarouselNext: typeof import('./src/components/ui/carousel/CarouselNext.vue')['default']
    CarouselPrevious: typeof import('./src/components/ui/carousel/CarouselPrevious.vue')['default']
    ContactComponent: typeof import('./src/components/ContactComponent.vue')['default']
    NavabarComponent: typeof import('./src/components/NavabarComponent.vue')['default']
    ReccomendCard: typeof import('./src/components/ReccomendCard.vue')['default']
    ReccomendCardComponent: typeof import('./src/components/ReccomendCardComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/tabs/TabsTrigger.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
