/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./src/components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./src/components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./src/components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./src/components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./src/components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./src/components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./src/components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./src/components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    ContactComponent: typeof import('./src/components/ContactComponent.vue')['default']
    NavabarComponent: typeof import('./src/components/NavabarComponent.vue')['default']
    ReccomendCard: typeof import('./src/components/ReccomendCard.vue')['default']
    ReccomendCardComponent: typeof import('./src/components/ReccomendCardComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/tabs/TabsTrigger.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
